tls:
  enabled: false
  crt: server.crt
  key: server.key

basicAuth:
  enabled: false
  username: admin
  password: admin

bearerAuth:
  enabled: false
  signingKey: my_secret_key

scripts:
  - name: speedtest
    script: /usr/local/bin/speedtest-exporter.sh
#  - name: test
#    script: ./examples/test.sh
#  - name: ping
#    script: ./examples/ping.sh
#  - name: helloworld
#    script: ./examples/helloworld.sh test
#  - name: curltest
#    script: ./bin/curltest
#  - name: showtimeout
#    script: ./examples/showtimeout.sh
#    timeout:
#      max_timeout: 60
#  - name: sleep
#    script: sleep 120
#    timeout:
#      enforced: true